package view;//GEN-LINE:variables

import dao.ClienteDAO;
import dao.FuncionarioDAO;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import model.Admin;
import model.Funcionario;
import model.Vendedor;

/**
 *
 * @author luizportel4
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    protected FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    protected ClienteDAO clienteDAO = new ClienteDAO();
 
    public LoginView() {
        this.setTitle("Realizar Login");
        initComponents();
        decoracao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        tfCPF = new javax.swing.JTextField();
        lbEsqueci = new javax.swing.JLabel();
        bttEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPF");

        jLabel2.setText("Senha");

        tfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaActionPerformed(evt);
            }
        });
        lbEsqueci.setFont(new java.awt.Font("Garuda", 0, 12)); // NOI18N
        lbEsqueci.setText("Esqueceu a senha? Clique aqui.");
        lbEsqueci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEsqueciMouseClicked(evt);
            }
        });

        bttEntrar.setText("Entrar");
        bttEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbEsqueci, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttEntrar)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(lbEsqueci)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)

                .addComponent(bttEntrar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        
    private void decoracao(){
        getContentPane().setBackground(Color.decode("#3f3f46"));
        jLabel1.setForeground(Color.decode("#fafaf9"));
        jLabel2.setForeground(Color.decode("#fafaf9"));
        lbEsqueci.setForeground(Color.decode("#fafaf9"));
        lbEsqueci.setText("<HTML><U>Esqueceu sua senha? Clique aqui!</U></HTML>");
        lbEsqueci.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        tfCPF.setBackground(Color.decode("#f3f4f6"));
        tfSenha.setBackground(Color.decode("#f3f4f6"));
        bttEntrar.setBackground(Color.decode("#38bdf8"));
        bttEntrar.setForeground(Color.decode("#fafaf9"));
        tfCPF.setForeground(Color.decode("#18181b"));
        tfSenha.setForeground(Color.decode("#18181b"));
    }
    private void tfSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void lbEsqueciMouseClicked(java.awt.event.MouseEvent evt) {                                       
        JOptionPane.showMessageDialog(null, "Que pena!","Esqueceu sua senha",JOptionPane.ERROR_MESSAGE);
    }                                      


    private void bttEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String cpf = tfCPF.getText();
        String senha = tfSenha.getText();
        Funcionario usuario = this.funcionarioDAO.findFuncionario(cpf, senha);
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "CPF e/ou senha incorrentos ou o funcionário não existe.");
        } else if (usuario instanceof Vendedor) {
            VendaView vendaView = new VendaView(usuario);
            vendaView.setVisible(true);
        } else if (usuario instanceof Admin) {
            AdminView adminView = new AdminView(usuario);
            adminView.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Usuário nâo encontrado");
        }
    }                                         

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton bttEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbEsqueci;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration                   
}
