/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import java.awt.Color;
import model.Cliente;

/**
 *
 * @author sonho
 */
public class RelatorioClienteView extends javax.swing.JFrame {
    ClienteDAO clienteDAO = new ClienteDAO();
    /**
     * Creates new form RelatorioClienteView
     */
    public RelatorioClienteView() {
        this.setTitle("Relatório de Clientes");
        initComponents();
        decoracao();
        for(Cliente c : clienteDAO.getClientes()){
            taListaClientes.append(c.toString());
        }
        
    }
    private void decoracao(){
        getContentPane().setBackground(Color.decode("#3f3f46"));
        jLabel1.setForeground(Color.decode("#fafaf9"));
        taListaClientes.setBackground(Color.decode("#f3f4f6"));
        taListaClientes.setForeground(Color.decode("#18181b"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaClientes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Clientes no Sistema");

        taListaClientes.setEditable(false);
        taListaClientes.setColumns(20);
        taListaClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taListaClientes.setForeground(new java.awt.Color(107, 114, 128));
        taListaClientes.setRows(5);
        jScrollPane1.setViewportView(taListaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taListaClientes;
    // End of variables declaration//GEN-END:variables
}
