/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProdutoDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author sonho
 */
public class RemoverProdutoView extends javax.swing.JFrame {
    ProdutoDAO produtoDAO = new ProdutoDAO();
    private AdminView main;
    /**
     * Creates new form RemoverProdutoView
     */
    public RemoverProdutoView() {
        initComponents();
        this.setTitle("Remover Produto");
        decoracao();
    }
    private void decoracao(){
        getContentPane().setBackground(Color.decode("#3f3f46"));
        lbInserirCodigo.setForeground(Color.decode("#fafaf9"));
        lbTitulo.setForeground(Color.decode("#fafaf9"));
        tfCodigoProduto.setBackground(Color.decode("#f3f4f6"));
        tfCodigoProduto.setForeground(Color.decode("#18181b"));
        btRemover.setBackground(Color.decode("#38bdf8"));
        btRemover.setForeground(Color.decode("#fafaf9"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        tfCodigoProduto = new javax.swing.JTextField();
        lbInserirCodigo = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Remover Produto");

        lbInserirCodigo.setText("Insira o código do produto");

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInserirCodigo)
                    .addComponent(tfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbTitulo)
                .addGap(32, 32, 32)
                .addComponent(lbInserirCodigo)
                .addGap(8, 8, 8)
                .addComponent(tfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btRemover)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja remover o produto do estoque?", "Remover Produto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirmar == JOptionPane.YES_OPTION){
           int codigo = Integer.parseInt(tfCodigoProduto.getText());
        for(int i = 0; i < produtoDAO.getProdutos().size(); i++){
            if(produtoDAO.getProdutos().get(i).getCodigo() == codigo){
                produtoDAO.removeProduto(i);
            }
        }
        JOptionPane.showMessageDialog(null, "Produto removido do estoque","Produto Removido",JOptionPane.WARNING_MESSAGE); 
        }else{
            JOptionPane.showMessageDialog(null, "Operação cancelada", "Operação cancelada", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btRemoverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel lbInserirCodigo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfCodigoProduto;
    // End of variables declaration//GEN-END:variables
}
